Move southernmost from column 0     0           0           0                   SOUTH       1           0           1
Move southernmost from column 1     1           0           1                   SOUTH       1           0           2
Move southernmost from column 2     2           0           2                   SOUTH       2           0           3
Move southernmost from column 3     3           0           3                   SOUTH       3           0           4
Move southernmost from column 4     4           0           4                   SOUTH       4           0           5
Move southernmost from column 5     5           0           5                   SOUTH       5           0           6
Move southernmost from column 6     6           0           6                   SOUTH       6           0           7
Move southernmost from column 7     7           0           7                   SOUTH       7           0           8
Move southernmost from column 8     8           0           8                   SOUTH       8           0           9
Move southernmost from column 9     9           0           9                   SOUTH       9           0           10
Move northernmost from column 0     0           9           10                  NORTH       0           9           11
Move northernmost from column 1     1           9           11                  NORTH       1           9           12
Move northernmost from column 2     2           9           12                  NORTH       2           9           13
Move northernmost from column 3     3           9           13                  NORTH       3           9           14
Move northernmost from column 4     4           9           14                  NORTH       4           9           14
Move northernmost from column 5     5           9           15                  NORTH       5           9           16
Move northernmost from column 6     6           9           16                  NORTH       6           9           17
Move northernmost from column 7     7           9           17                  NORTH       7           9           18
Move northernmost from column 8     8           9           18                  NORTH       8           9           19
Move northernmost from column 9     9           9           19                  NORTH       9           9           20
Move westernmost from row 0         0           0           20                  WEST        0           0           21
Move westernmost from row 1         0           1           21                  WEST        0           1           22
Move westernmost from row 2         0           2           22                  WEST        0           2           23
Move westernmost from row 3         0           3           23                  WEST        0           3           24
Move westernmost from row 4         0           4           24                  WEST        0           4           25
Move westernmost from row 5         0           5           25                  WEST        0           5           26
Move westernmost from row 6         0           6           26                  WEST        0           6           27
Move westernmost from row 7         0           7           27                  WEST        0           7           28
Move westernmost from row 8         0           8           29                  WEST        0           8           30
Move westernmost from row 9         0           9           30                  WEST        0           9           31
Move easternmost from row 0         9           0           32                  EAST        9           0           33
Move easternmost from row 1         9           1           33                  EAST        9           1           34
Move easternmost from row 2         9           2           34                  EAST        9           2           35
Move easternmost from row 3         9           3           35                  EAST        9           3           36 
Move easternmost from row 4         9           4           36                  EAST        9           4           37
Move easternmost from row 5         9           5           37                  EAST        9           5           38
Move easternmost from row 6         9           6           38                  EAST        9           6           39
Move easternmost from row 7         9           7           39                  EAST        9           7           40
Move easternmost from row 8         9           8           41                  EAST        9           8           42
Move easternmost from row 9         9           9           42                  EAST        9           9           43